### ISSUE TITLE
Blocknet dex app rewrites .conf files?

### ISSUE THREAD

**Issue by Coinomatron** [blocknetdx/blocknet#439]
I was tinkering with setting up the dex, when I noticed the program can rewrite the .conf files of the associated wallets (rpc-credentials). This also causes the wallets to become unresponsive, as they no longer accept commands from the -cli with pre-rewritten .conf info. But just the rewriting of the conf file seems like a big security flaw to me, but maybe I'm wrong.

**Comment by HanniAbu** [comment]
Hi @Coinomatron, no files are overwritten unless you're going through the automated setup.

**Comment by Coinomatron** [comment]
Hi, yes I noticed that, after my manual setup kept giving configuration errors, so I tried the automated configuration (it didn't work after that either, by the way) The bigger issue to me, is that I suppose the application could, if malicious code was somehow inserted, clean out the wallets it connects to. That means that this dex also requires trust. Perhaps I'm overlooking things, so correct me if I'm wrong.

**Comment by HanniAbu** [comment]
As far as malicious code is concerned, there is none, but you're free to review it yourself, build from source, and/or even modify the code if you'd like. Everything is open source and can be found in the Block DX repo (this issue is currently on the Blocknet repo):
https://github.com/blocknetdx/block-dx

If you'd like help with the manual setup, feel free to join our Discord. There's many people there that will be able to assist you: https://discord.gg/X6UhcB3

**Comment by Coinomatron** [comment]
Ok, thanks.
